# Tell GitHub Pages to pull the Just the Docs theme remotely
remote_theme: pmarsceill/just-the-docs

# Any plugins you want (these are supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs options:
title: "My Jekyll Demo"
description: "A quick demo of Just the Docs"
search_enabled: true
nav_order:
  - Home
  - About
