# Site settings
title: "My Jekyll Demo"
description: "A quick demo of Just the Docs"
baseurl: ""      # leave blank if serving at /<repo-name>/
url: "https://EjkHub.github.io/jekyll-demo"

# Theme
theme: just-the-docs

# Navigation for Just the Docs
nav_order:
  - Home
  - About

# Optional features
search_enabled: true
table_of_contents: any

# Plugins
plugins:
  - jekyll-feed

# (remove any `remote_theme:` lines—using the gem directly)
