remote_theme: pmarsceill/just-the-docs

# Optional: if you need to list plugins, these are already in the GH-Pages gem:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs settings
title: "My Jekyll Demo"
description: "A quick demo of Just the Docs"
nav_order:
  - Home
  - About

# Enable the built-in search index
search_enabled: true
search_json:    true
search_posts:   true        # only if you want blog posts
collections:
  specs:
    output: true            # example custom collection
search:
  collections: [specs]      # whitelist it for the index

# If this is a project page (not your user/org root site):
baseurl: "/jekyll-demo"

# logo: /assets/images/origColor.jpg
# logo: /assets/images/Axiom_logo.svg

just_the_docs:
  custom_css:
    - "/assets/css/logo.css"



