remote_theme: pmarsceill/just-the-docs

# Optional: if you need to list plugins, these are already in the GH-Pages gem:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs settings
title: "My Jekyll Demo"
description: "A quick demo of Just the Docs"
nav_order:
  - Home
  - About

# Enable the built-in search index
search_enabled: true
search_json:    true

# If this is a project page (not your user/org root site):
baseurl: "/jekyll-demo"
