#remote_theme: pmarsceill/just-the-docs   #old location still works but may not receive updates
#new location is the officially maintained version
# remote_theme: just-the-docs/just-the-docs@v0.650   #threw up with bad version
remote_theme: just-the-docs/just-the-docs@v0.10.1

# Optional: if you need to list plugins, these are already in the GH-Pages gem:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: "The Way Up"
description: "Just the Docs"

# tells Jekyll to treat your docs directory as the root container for your markdown pages.
collections_dir: docs

nav_order:
  - Home
  - About

# Enable the built-in search index
search_enabled: true
search_json:    true
search_posts:   true        # only if you want blog posts
collections:
  specs:
    output: true            # example custom collection
search:
  collections: [specs]      # whitelist it for the index

# If this is a project page (not your user/org root site):
baseurl: "/jekyll-demo"

# logo: /assets/images/origColor.jpg
# logo: /assets/images/Axiom_logo.svg

# only just_the_docs: allowed
just_the_docs:
  custom_css:
    - "/assets/css/logo.css"

  collections_dir: docs




