# .github/workflows/jekyll-pages.yml
name: Build and deploy Jekyll site with Bundler

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # to clone your repo
      pages: write      # to push to GitHub Pages
      id-token: write   # needed by deploy action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.x"  # match your local Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build --destination _site

      - name: Upload _site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
